### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [Donskoy-Andrey/linked_list#1]
1) переменные `_data` и `_number_of_lines` не должны быть полями класса LinkedList, по своей сути это временные переменные, которые используются только в конструкторе реализованного посредством чтения из файла.
2) У вас учетка памяти, вы не очищаете сам список, то есть нужно пройти по всем элементам и удалить их.

**Comment by Donskoy-Andrey** [comment]
@dzheltkov Исправил. Теперь значения из 1 пункта убраны из класса. Утечку памяти предотвратил - теперь ноды, которые удаляются с помощью метода deleteElement, также удаляются из памяти.

**Comment by dzheltkov** [comment]
Утечка не вполне устранена -- у вас деструктор и метод deallocate не очищают память.
Вам при уничтожении объекта нужно проутись по указателям на все эолементы списка и очистить память.

**Comment by dzheltkov** [comment]
Задание зачтено.
